package me.battledash.kyber.types.pojo;

import lombok.Data;
import lombok.EqualsAndHashCode;
import me.battledash.kyber.fs.ebx.EbxPOJO;

@Data
@EqualsAndHashCode(callSuper = true)
public class Blueprint extends EntityBusData implements EbxPOJO {

    private boolean HasSandbox = true;
    private boolean IsAutoGenerated;
    private String Description;
    private GameObjectData[] Objects;
    private GameObjectData SchematicsClass; // TODO: 4/15/2022 Implement SchematicsClassInfoAsset
    private Blueprint VariableTableOverride;
    private GameObjectData ClientSchematics;
    private GameObjectData ServerSchematics;
    private long SchematicsBusFieldOffset;

}
