package me.battledash.kyber.types.pojo;

import lombok.Data;
import lombok.EqualsAndHashCode;
import me.battledash.kyber.fs.ebx.EbxPOJO;

import java.util.UUID;

@Data
@EqualsAndHashCode(callSuper = true)
public class DynamicDataContainer extends Asset implements EbxPOJO {

    private DataField[] Fields;

    @Data
    public static class DataField implements EbxPOJO {
        private String Name;
        private String Description;
        private String Category;
        private String FieldType;
        private UUID TypeGuid;

        private boolean ExposedInSubWorldInterface;
        private boolean IsAutoGenerated;
        private boolean IsSharedField;

        private String Value;
        private Object BoxedValue;
        private Object ValueType;
        private Object ValueRef;

        private int Id;
        private Vec2 SchematicNodePosition;
    }

}
